#!/usr/bin/env bash

# variables settable by user
: ${SVM_TRAIN_CMD:=svm-train}
: ${SVM_PREDICT_CMD:=svm-predict}

############################################################
set -e
export LC_ALL=C

usage(){
    cat 1>&2 <<'EOF'
usage: herisvm-train [HERISVM_OPTIONS] training_set -- SVM_TRAIN_OPTIONS
HERISVM_OPTS:
      -h                   help message
      -v n                 n-fold cross validation mode (mandatory option)
      -s                   all folds statistic     
      -p <precision_opts>  options passed to precision(1)
Examples: 
  Ex1: export SVM_TRAIN_CMD='liblinear-train'
       export SVM_PREDICT_CMD='liblinear-predict'
       herisvm-train -v 5 -- -s 4 -q
  Ex2: export SVM_TRAIN_CMD='gb-train'
       export SVM_PREDICT_CMD='gb-predict'
       herisvm-train -v 4 -- -gb -opt -io -ns
EOF
}

while getopts hsp:v: f; do
    case "$f" in
	'?')
	    usage
	    exit 1;;
	h)
	    usage
	    exit 0;;
	v)
	    number_of_folds="$OPTARG";;
	p)
	    precision_args="$precision_args $OPTARG";;
	s)
	    fold_statistics="ok";;
    esac
done
shift `expr $OPTIND - 1`

while test "$#" -gt 0; do
    case "$1" in
	--)
	    shift
	    break;;
	*)
	    print_sh=`printf '%q' "$1"`
	    files="$files $print_sh"
	    shift;;
    esac
done

# "$@" -- svm options

if test -z $number_of_folds; then
    echo 'Option -v is mandatory, run herisvm-train -h for details' 1>&2
    exit 1
fi

trap 'rm -rf $TMP_DIR_SVM' 0 INT TERM
export TMP_DIR_SVM=`mktemp -d /tmp/svm.XXXXXX`

export set_count="$number_of_folds"
cat $files | split_set
last=`expr $number_of_folds - 1`

for i in `seq 0 $last` #{1..$number_of_folds}
do
    eval "${SVM_TRAIN_CMD} $@ '$TMP_DIR_SVM/train$i.txt' '$TMP_DIR_SVM/svm$i.bin'" > "$TMP_DIR_SVM/train_stderr${i}" &
done

wait

for i in `seq 0 $last`
do
    ${SVM_PREDICT_CMD} "$TMP_DIR_SVM/test$i.txt" "$TMP_DIR_SVM/svm$i.bin" \
	"$TMP_DIR_SVM/result${i}.txt" \
	2> "$TMP_DIR_SVM/predict_stderr${i}" \
	>  "$TMP_DIR_SVM/predict_stdout${i}"
done

wait

rm -f "$TMP_DIR_SVM/golden_tags" "$TMP_DIR_SVM/result.txt"
    
for i in `seq 0 $last`
do
    if test -n "$fold_statistics"; then
	echo "Fold $i statistics"
    fi
    awk '{print $1}' "$TMP_DIR_SVM/test$i.txt" > "$TMP_DIR_SVM/golden_tags${i}"

    if test -n "$fold_statistics"; then
	precision "$TMP_DIR_SVM/golden_tags${i}" "$TMP_DIR_SVM/result${i}.txt"
	echo ''
    fi

    cat "$TMP_DIR_SVM/golden_tags${i}" >> "$TMP_DIR_SVM/golden_tags"
    cat "$TMP_DIR_SVM/result${i}.txt"  >> "$TMP_DIR_SVM/result.txt"
done

echo 'Total statistics'
precision $precision_args "$TMP_DIR_SVM/golden_tags" "$TMP_DIR_SVM/result.txt"
