#!/usr/bin/env ruby

set_count = ENV["set_count"].to_f

#############################################
#### to create ranges and

ranges = []
i = set_count
files = []
while i > 0
  range = (i-1)/set_count...i/set_count
  ranges << range
  i -= 1
  name_train = "train" + "#{i.to_i}"
  name_test = "test" + "#{i.to_i}"
  #puts name_train
  files << File.open(name_test+".txt", 'w')
  files << File.open(name_train+".txt", 'w')
end
# = File.open(ENV["tmp"]"+"/" ".txt", 'w')
#puts files.inspect

#############################################
####

while line = gets
  line.chomp!
  line_number = rand.to_f
  #puts line_number.class
  ranges.each_with_index { |x, ind|
#    puts line_number
#    puts x.class
    if x.include?(line_number)
      files[ind*2].puts line
#      puts true
    else
      files[ind*2+1].puts line
#      puts false
    end
  }
end

files.each { |x|
  x.close
}
